apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.hedgedoc.name }}-uploads-pv
  labels:
    type: hedgedocupload
spec:
  storageClassName: local-path
  capacity:
    storage: {{ .Values.volume.capacity.storage }}
  accessModes:
    - {{ .Values.volume.accessModes }}
  hostPath:
    path: {{ .Values.hedgedoc.mountPath }}/uploads
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.hedgedoc.name }}-db-pv
  labels:
    type: hedgedocdb
spec:
  storageClassName: local-path
  capacity:
    storage: {{ .Values.volume.capacity.storage }}
  accessModes:
    - {{ .Values.volume.accessModes }}
  hostPath:
    path: {{ .Values.hedgedoc.mountPath }}/db
---