apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.hedgedoc.name }}-uploads-pv
  labels:
    type: hedgedocupload
spec:
{{- if .Values.volume.storageClassNameEnabled }}
  storageClassName: {{ .Values.volume.storageClassName }}
{{- end }}
  capacity:
    storage: {{ .Values.volume.capacity.storage }}
  accessModes:
    - {{ .Values.volume.accessModes }}
  hostPath:
    path: {{ .Values.hedgedoc.mountPath }}/uploads
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.hedgedoc.name }}-db-pv
  labels:
    type: hedgedocdb
spec:
{{- if .Values.volume.storageClassNameEnabled }}
  storageClassName: {{ .Values.volume.storageClassName }}
{{- end }}
  capacity:
    storage: {{ .Values.volume.capacity.storage }}
  accessModes:
    - {{ .Values.volume.accessModes }}
  hostPath:
    path: {{ .Values.hedgedoc.mountPath }}/db