{{- if and .Values.hedgedoc.enabled .Values.hedgedoc.database.external.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.hedgedoc.database.external.secretName }}
  namespace: {{ .Values.hedgedoc.nameSpace }}
type: Opaque
stringData:
  {{ .Values.hedgedoc.database.external.userKey }}: {{ .Values.hedgedoc.database.external.testUser | default "changeme" | quote }}
  {{ .Values.hedgedoc.database.external.passwordKey }}: {{ .Values.hedgedoc.database.external.testPassword | default "changeme" | quote }}
{{- end }}

