apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mongodb.name }}-statefulset
spec:
  replicas: {{ .Values.mongodb.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mongodb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.name }}
    spec:
      containers:
        - name: {{ .Values.mongodb.name}}
          image: "{{ .Values.mongodb.deployment.image.name}}:{{ .Values.mongodb.deployment.image.tag }}"
          ports:
            - containerPort: {{ .Values.mongodb.deployment.port }}
          volumeMounts:
            - mountPath: {{ .Values.mongodb.deployment.volumemounts.mountPath }}
              name: {{ .Values.mongodb.deployment.volumemounts.name }}
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes: [ {{ .Values.mongodb.pvc.accessModes }} ]
        resources:
          requests:
            storage: {{ .Values.mongodb.pvc.resources.requests.storage }}