apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mongodb.volumeClaimTemplates.name }}-pv
  labels:
    type: mongodb
spec:
  {{- if .Values.volume.storageClassNameEnabled }}
  storageClassName: {{ .Values.volume.storageClassName }}
  {{- end }}
  capacity:
    storage: {{ .Values.volume.capacity.storage }}
  accessModes:
    - {{ .Values.volume.accessModes }}
  hostPath:
    path: {{ .Values.mongodb.statefulset.mountPath }}