apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}-service
  namespace: {{ .Values.treasury.nameSpace}}
spec:
  selector:
    app: {{ .Values.mongodb.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.mongodb.statefulset.port }}
      targetPort: {{ .Values.mongodb.service.port }}
  type: {{ .Values.mongodb.service.type }}