apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mongodb.volumeClaimTemplates.name }}-pv
  labels:
    type: mongodb
spec:
  storageClassName: local-path
  capacity:
    storage: {{ .Values.volume.capacity.storage }}
  accessModes:
    - {{ .Values.volume.accessModes }}
  hostPath:
    path: {{ .Values.mongodb.statefulset.mountPath }}