# helmcharts/templates/mongodb/mongodb_headless_service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}-headless
  namespace: {{ .Values.treasury.nameSpace}}
spec:
  ports:
    - port: {{ .Values.mongodb.statefulset.port }}
      name:  {{ .Values.mongodb.name }}
  clusterIP: None
  selector:
    app: {{ .Values.mongodb.name }}