apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongoexpress.name }}-app
  namespace: {{ .Values.treasury.nameSpace}}

spec:
  selector:
    matchLabels:
      app: {{ .Values.mongoexpress.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongoexpress.name }}
    spec:
      containers:
        - name: {{ .Values.mongoexpress.name }}
          image: "{{ .Values.mongoexpress.image.name }}:{{ .Values.mongoexpress.image.tag }}"
          env:
            - name: ME_CONFIG_SITE_SESSIONSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongoexpress.name }}-secret
                  key: siteSessionSecret
            - name: ME_CONFIG_SITE_COOKIESECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongoexpress.name }}-secret
                  key: siteCookieSecret
            - name: ME_CONFIG_BASICAUTH
              value: "true"
            - name: ME_CONFIG_BASICAUTH_USERNAME
              {{- if and .Values.mongoexpress.basicAuth .Values.mongoexpress.basicAuth.username }}
              value: "{{ .Values.mongoexpress.basicAuth.username }}"
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongoexpress.name }}-secret
                  key: basicAuthUsernameMongoExpress
              {{- end }}
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              {{- if and .Values.mongoexpress.basicAuth .Values.mongoexpress.basicAuth.password }}
              value: "{{ .Values.mongoexpress.basicAuth.password }}"
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongoexpress.name }}-secret
                  key: basicAuthPassMongoExpress
              {{- end }}
            - name: ME_CONFIG_OPTIONS_DOCUMENT_LIMIT
              value: "100"
            - name: ME_CONFIG_MONGODB_URL
              value: '{{ .Values.mongoexpress.mongodbUrl | default (printf "mongodb://%s-service.%s.svc.cluster.local:%v" .Values.mongodb.name .Values.treasury.nameSpace .Values.mongodb.service.port) }}'
          ports:
            - containerPort: {{ .Values.mongoexpress.deployment.port }}