apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretstore.name }}
spec:
  provider:
    azurekv:
      vaultUrl: {{ .Values.secretstore.vaultUrl }}
      authType: ServicePrincipal
      tenantId: {{ .Values.secretstore.tenantId }}
      authSecretRef:
        clientId:
          name: {{ .Values.servicePrincipal.name }}-secret
          namespace: external-secrets
          key: ClientID
        clientSecret:
          name: {{ .Values.servicePrincipal.name }}-secret
          key: ClientSecret
          namespace: external-secrets
