apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-kv
  namespace: external-secrets
spec:
  provider:
    azurekv:
      vaultUrl: "https://treasurykeyvault.vault.azure.net/"
      authType: ServicePrincipal
      tenantId: "71b67176-40e1-4d4e-80fe-9251918425b2"
      authSecretRef:
        clientId:
          name: azure-sp-secret
          key: ClientID
        clientSecret:
          name: azure-sp-secret
          key: ClientSecret
