## MongoDB Express configuration
mongoexpress:
  name: mongo-express
  image:
    name: mongo-express
    tag: latest
  deployment:
    port: 8081
  service:
    port: 8081
    type: ClusterIP
  ingress:
    className: traefik
    pathType: ImplementationSpecific
    port: 8081
    host: mongoexpress.example.com
## MongoDB configuration

mongodb:
  name: mongodb
  statefulset:
    image:
      name: mongo
      tag: latest
    port: 27017
    replicaCount: 1
    mountPath: /data/db
    volumemounts:
      mountPath: /data/db
  service:
    port: 27017
    type: LoadBalancer
  volumeClaimTemplates:
    name: mongo-storage
    accessModes: ReadWriteOnce
    resources:
      requests:
        storage: 1Gi