
## MongoDB (Dev: In-Cluster StatefulSet aktiv; app verbindet sich mit dem In-Cluster Service)
mongodb:
  enabled: true
  app:
    host: mongodb-service.treasury.svc.cluster.local
    auth: false

## general
ingress:
  className: traefik
volume:
  storageClassName: local-path
  storageClassNameEnabled: true

## Hedgedoc configuration
hedgedoc:
  nodeSelector:
  ingress:
    host: hedgedoc-dev.biester.vip
    tlsEnabled: true
  database:
    internal:
      enabled: false
    external:
      enabled: true
      host: kubitosdell4gb
      port: 5432
      name: hedgedoc
      secretName: hedgedoc-db-credentials
      userKey: username
      passwordKey: password
      sslmode: disable
      # Nur zum Testen (später durch ExternalSecret ersetzen):
      testUser: hedgedoc
      testPassword: hedgedoc

treasury:
  nodeSelector:
  ingress:
    host: treasury-dev.biester.vip
    tlsEnabled: true

