apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hedgedoc.name }}-db
  namespace: {{ .Values.hedgedoc.nameSpace }}
spec:
  ports:
    - port: 5432
  selector:
    app: {{ .Values.hedgedoc.name }}-db