apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.hedgedoc.name }}-db
  namespace: {{ .Values.hedgedoc.nameSpace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.hedgedoc.name }}-db
  template:
    metadata:
      labels:
        app: {{ .Values.hedgedoc.name }}-db
    spec:
      containers:
        - name: postgres
          image: postgres:13.4-alpine
          env:
            - name: POSTGRES_USER
              value: hedgedoc
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: hedgedoc
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: {{ .Values.hedgedoc.name }}-db-pvc