project: treasury
source:
  repoURL: https://github.com/BiesterVictor/treasury
  path: helmcharts
  targetRevision: HEAD
  helm:
    valueFiles:
      - values.yaml
destination:
  server: https://kubernetes.default.svc
  namespace: treasury
syncPolicy:
  automated: {}
  syncOptions:
    - ApplyOutOfSyncOnly=true
  retry:
    limit: 2
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m0s