apiVersion: apps/v1
kind: Deployment
metadata:
  name: treasury
  namespace: {{ .Values.treasury.nameSpace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treasury
  template:
    metadata:
      labels:
        app: treasury
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: treasury
          image: "{{ .Values.treasury.image.name }}:{{ .Values.treasury.image.tag }}"
          command: ["java", "-jar", "app.jar"]
          args: ["--spring.profiles.active=kubitos"]
          env:
            - name: MAILJET_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.treasury.name }}-secret
                  key: mailJetApiKey
            - name: MAILJET_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.treasury.name }}-secret
                  key: mailJetApiSecret
          ports:
            - containerPort: 8080
